name: swps_synchronization_study_env
channels:
  - defaults
dependencies:
  - python
  - pandas
  - pip
  - pip:
      - ../python-utils[plotly]
      - ../python-utils[matplotlib]
      - ../python-utils[dataframe]
      - ../python-utils[math_signals]

